version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache:
- '%USERPROFILE%\.nuget\packages'
nuget:  
  disable_publish_on_pr: true
init:
  - cmd: git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./atmosphere-web.csproj --verbosity m
build_script:
  # this will do the build of backend, restore npm and run webpack
  - cmd: dotnet publish ./atmosphere-web.csproj